# AUTOGENERATED! DO NOT EDIT! File to edit: 00_math.ipynb (unless otherwise specified).

__all__ = ['comb', 'binom', 'Wilson_var', 'Wald_var']

# Cell
import numpy as np
from scipy.special import factorial

# Cell
def comb(n, k):
    """Vectorized combination"""
    return factorial(n) / (factorial(k) * factorial(n-k))

# Cell
def binom(k, n, p):
    """Vectorized binomial function"""
    return comb(n,k) * p**k * (1-p)**(n-k)

# Cell
def Wilson_var(p, N, z=1.96):
    """Wilson estimator of binomial variance"""
    return z**2 * (p*(1-p)/N + z**2/(4*N**2)) / (1+z**2/N)**2

# Cell
def Wald_var(p, N):
    """Wald estimator of binomial variance (known issues, better use Wilson)"""
    return p * (1-p) / N