# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_examples.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/09_examples.ipynb 3
import qsample as qs
import numpy as np
import matplotlib.pyplot as plt
