# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_utils.ipynb.

# %% auto 0
__all__ = ['save', 'load']

# %% ../nbs/02_utils.ipynb 3
import dill as pickle

# %% ../nbs/02_utils.ipynb 4
def save(data, path):
    """Save data to path

    Parameters
    ----------
    path : str
        File path to save to
    data : *
        Data to write to path
    """
    with open(path, 'wb') as fp:
        pickle.dump(data, fp)

# %% ../nbs/02_utils.ipynb 5
def load(path):
    """Load data from path

    Parameters
    ----------
    path : str
        File path to load from
        
    Returns
    -------
    *
        Loaded data
    """
    with open(path, 'wb') as fp:
        data = pickle.load(fp)
    return data
