# AUTOGENERATED! DO NOT EDIT! File to edit: 05a_samplers.circuit_samplers.ipynb (unless otherwise specified).

__all__ = ['Sampler', 'SubsetSampler', 'calc_w_max']

# Cell
import qsam.math as math
from ..circuit import make_hash, unpack
import qsam.samplers.callbacks as cb
from .subset_helper import *
from ..fault_generators import Depolarizing

import numpy as np
import itertools as it
from tqdm.auto import tqdm

# Cell

class Sampler:

    def __init__(self, circuit, simulator, fault_gen, fail_patterns):
        self.circuit = circuit
        self.simulator = simulator
        self.n_qubits = circuit.n_qubits
        self.fail_patterns = fail_patterns

        fault_gen.configure(circuit)
        self.fault_gen = fault_gen

        self.cnts = np.zeros(len(self.fault_gen.p_phy))
        self.fail_cnts = np.zeros(len(self.fault_gen.p_phy))

    def stats(self, p_idx=None, var_fn=math.Wilson_var, **kwargs):
        if p_idx == None:
            rate = self.fail_cnts / self.cnts
            var = var_fn(rate, self.cnts)
        else:
            rate = self.fail_cnts[p_idx] / self.cnts[p_idx]
            var = var_fn(rate, self.cnts[p_idx])

        return rate, np.sqrt(var), 0.0, 0.0

    def run(self, n_samples, callbacks=[]):

        if not isinstance(callbacks, cb.CallbackList):
            callbacks = cb.CallbackList(sampler=self, callbacks=callbacks)
        callbacks.on_sampler_begin()

        for i, p_phy in enumerate(tqdm(self.fault_gen.p_phy, desc='Total')):
            self.stop_sampling = False
            self.p_idx = i

            for _ in tqdm(range(n_samples), desc=f'p_phy={",".join(list(f"{p:.2E}" for p in p_phy))}', leave=True):
                sim = self.simulator(self.n_qubits)
                faults = self.fault_gen.faults_from_probs(p_phy)
                fault_circuit = self.fault_gen.gen_circuit(len(self.circuit), faults)
                msmt = sim.run(self.circuit, fault_circuit)
                if int(msmt,2) in self.fail_patterns:
                    self.fail_cnts[i] += 1
                self.cnts[i] += 1

                callbacks.on_circuit_end(locals())
                if self.stop_sampling: break

        callbacks.on_sampler_end()

# Cell
class SubsetSampler:

    def __init__(self, circuit, simulator, fault_gen, fail_patterns, w_max, p_max, w_exclude={}):
        self.circuit = circuit
        self.simulator = simulator
        self.n_qubits = circuit.n_qubits

        fault_gen.configure(circuit)
        self.fault_gen = fault_gen

        self.fail_patterns = fail_patterns

        p_max = np.array([p_max]) if isinstance(p_max, float) else np.array(p_max)
        assert len(p_max) == len(self.fault_gen.partition_names)

        self.w_vecs = circuit_weight_vectors(w_max, w_exclude)
        self.w_max = w_max
        self.set_range()
        self.Aws_pmax = circuit_subset_occurence(self.fault_gen.partitions, self.w_vecs, p_max)
        self.Aws_pmax_inclusive = circuit_subset_occurence(self.fault_gen.partitions, circuit_weight_vectors(w_max), p_max)

        self.cnts = np.zeros((len(self.w_vecs))) + 1 # one virtual sample to avoid div0
        self.fail_cnts = np.zeros((len(self.w_vecs)))

    def set_range(self, err_params=None):
        if err_params: self.fault_gen.__init__(err_params)
        self.Aws = circuit_subset_occurence(self.fault_gen.partitions, self.w_vecs, self.fault_gen.p_phy)
        self.Aws_inclusive = circuit_subset_occurence(self.fault_gen.partitions, circuit_weight_vectors(self.w_max,{}), self.fault_gen.p_phy)

    @property
    def ss_rate(self):
        cnts = self.cnts - 1 if np.all(self.cnts > 1) else self.cnts
        return ( self.fail_cnts / (cnts) )[:,None]

    def stats(self, const='Aws', var_fn=math.Wilson_var, **kwargs):
        if const == 'Aws': Aws, Aws_inclusive = self.Aws, self.Aws_inclusive
        elif const == 'Aws_pmax': Aws, Aws_inclusive = self.Aws_pmax[:,None], self.Aws_pmax_inclusive[:,None]
        v_L = np.sum( [Aws[w]**2 * var_fn(self.ss_rate[w], self.cnts[w]) for w in range(len(self.w_vecs))], axis=0 )
        p_L = np.sum(Aws * self.ss_rate, axis=0)
        if isinstance(v_L, np.ndarray) and isinstance(p_L, int):
            p_L = np.zeros_like(v_L)
        delta = 1 - np.sum(Aws_inclusive, axis=0)
        return p_L, np.sqrt(v_L), delta, 0.0

    def run(self, n_samples, callbacks=[]):

        if not isinstance(callbacks, cb.CallbackList):
            callbacks = cb.CallbackList(sampler=self, callbacks=callbacks)

        self.stop_sampling = False
        callbacks.on_sampler_begin()

        for i in tqdm(range(n_samples), desc='Total'):

            callbacks.on_circuit_begin()

            sim = self.simulator(self.n_qubits)
            w_idx = self.cnts.argmin() # balanced weight selector
            w_vec = self.w_vecs[w_idx]
            faults = self.fault_gen.faults_from_weights(w_vec)
            fault_circuit = self.fault_gen.gen_circuit(len(self.circuit), faults)
            msmt = sim.run(self.circuit, fault_circuit)
            if int(msmt,2) in fail_patterns:
                self.fail_cnts[w_idx] += 1
            self.cnts[w_idx] += 1

            callbacks.on_circuit_end(locals())
            if self.stop_sampling: break

        callbacks.on_sampler_end()

# Cell
#hide

def calc_w_max(p_max, delta_max, n_partition_elems):
    """Calculate weight cutoff at p_max for delta_max"""

    delta = 1
    for w_max in range(n_partition_elems+1):
        delta -= math.binom(w_max, n_partition_elems, p_max)
        if delta < delta_max:
            break
    return w_max