# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"patch": "00_nbtools.ipynb",
         "Simulator": "01_simulator.ipynb",
         "Circuit": "02_circuit.ipynb",
         "unpack": "02_circuit.ipynb",
         "Circuit.qubits": "02_circuit.ipynb",
         "Circuit.n_qubits": "02_circuit.ipynb",
         "partition": "02_circuit.ipynb"}

modules = ["nbtools.py",
           "simulator.py",
           "circuit.py"]

doc_url = "https://dpwinter.github.io/qsam/"

git_url = "https://github.com/dpwinter/qsam/tree/master/"

def custom_doc_links(name): return None
