# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"comb": "00_math.ipynb",
         "binom": "00_math.ipynb",
         "Wilson_var": "00_math.ipynb",
         "Wald_var": "00_math.ipynb",
         "Circuit": "01_circuit.ipynb",
         "unpack": "01_circuit.ipynb",
         "partition": "01_circuit.ipynb",
         "freeze": "01_circuit.ipynb",
         "make_hash": "01_circuit.ipynb",
         "Protocol": "02_protocol.ipynb",
         "draw_protocol": "02_protocol.ipynb",
         "default_fns": "02_protocol.ipynb",
         "iterate": "02_protocol.ipynb",
         "save_protocol": "02_protocol.ipynb",
         "load_protocol": "02_protocol.ipynb",
         "CircuitRunnerMixin": "03a_simulators.simulator_mixins.ipynb",
         "pauli_product_phase": "03b_simulators.chp.ipynb",
         "MeasureResult": "03b_simulators.chp.ipynb",
         "ChpSimulator": "03b_simulators.chp.ipynb",
         "Depolar": "04_fault_generators.ipynb",
         "ONE_QUBIT_FAULTS": "04_fault_generators.ipynb",
         "TWO_QUBIT_FAULTS": "04_fault_generators.ipynb",
         "ONE_QUBIT_GATES": "05b_samplers.protocol_samplers.ipynb",
         "TWO_QUBIT_GATES": "05b_samplers.protocol_samplers.ipynb",
         "GATE_GROUPS": "05b_samplers.protocol_samplers.ipynb",
         "Sampler": "05b_samplers.protocol_samplers.ipynb",
         "SubsetSampler": "05b_samplers.protocol_samplers.ipynb",
         "calc_w_max": "05b_samplers.protocol_samplers.ipynb",
         "calc_subset_occurances": "05b_samplers.protocol_samplers.ipynb",
         "remap": "05b_samplers.protocol_samplers.ipynb"}

modules = ["math.py",
           "circuit.py",
           "protocol.py",
           "simulators/simulator_mixins.py",
           "simulators/chp.py",
           "fault_generators.py",
           "samplers/circuit_samplers.py",
           "samplers/protocol_samplers.py"]

doc_url = "https://dpwinter.github.io/qsam/"

git_url = "https://github.com/dpwinter/qsam/tree/master/"

def custom_doc_links(name): return None
