# AUTOGENERATED! DO NOT EDIT! File to edit: 00_nbtools.ipynb (unless otherwise specified).

__all__ = ['patch']

# Cell
import functools

# export
def patch(cls):
    def decorate(cls,func):
        setattr(cls,func.__name__,func)
        return func
    return functools.partial(decorate, cls)