# AUTOGENERATED! DO NOT EDIT! File to edit: 05_samplers.ipynb (unless otherwise specified).

__all__ = ['ONE_QUBIT_GATES', 'TWO_QUBIT_GATES', 'MEAS_GATES', 'GATE_GROUPS', 'Sampler', 'calc_subset_occurances',
           'remap', 'SubsetSampler', 'calc_w_max']

# Cell
import qsam.math as math
from .circuit import partition, make_hash, unpack
from .fault_generators import Depolar
from .protocol import iterate

import numpy as np
import itertools as it
import networkx as nx

# Cell
ONE_QUBIT_GATES = {'H', 'X', 'Z'}
TWO_QUBIT_GATES = {'CNOT'}
MEAS_GATES = {'measure'}

GATE_GROUPS = {'p': ONE_QUBIT_GATES | TWO_QUBIT_GATES | MEAS_GATES,
               'p1': ONE_QUBIT_GATES,
               'p2': TWO_QUBIT_GATES,
               'p_meas': MEAS_GATES
               }

# Cell
class Sampler:
    def __init__(self, protocol, simulator):
        self.protocol = protocol
        self.simulator = simulator
        self.n_qubits = len(set(q for c in protocol._circuits.values() for q in unpack(c)))

        # self.p_phy_per_partition = np.vstack(list(err_params.values())).T
        # self.partitions = map_dict(protocol._circuits, lambda _,circuit: [partition(circuit, GATE_GROUPS[g]) for g in err_params.keys()])
        # self.fault_gens = map_dict(protocol._circuits, lambda _,circuit: Depolar(len(circuit)))


    def run(self, n_samples, sample_range, err_params, var=math.Wilson_var, eval_fns=None):
        # fail_cnts = np.zeros((self.p_phy_per_partition.shape[0])) # one fail counter per p_phys
        fail_cnts = np.zeros(len(sample_range)) # one fail counter per sample point

        # for i, p_phy in enumerate(self.p_phy_per_partition):

        for i,sample_pt in enumerate(sample_range): # n_samples at sample_pt

            p_phy = np.array(list(err_params.values())) * sample_pt

            for _ in range(n_samples):

                sim = self.simulator(self.n_qubits)
                p_it = iterate(self.protocol, eval_fns)
                node = next(p_it)

                while node:

                    if node == 'EXIT':
                        fail_cnts[i] += 1
                        break
                    else:
                        circuit = self.protocol.circuit_from_node(node)
                        partitions = [partition(circuit, GATE_GROUPS[k]) for k in err_params.keys()] # => some kind of cache to not calc every time anew!
                        faults = Depolar.faults_from_probs(partitions, p_phy)
                        fault_circuit = Depolar.gen_circuit(len(circuit), faults)
                        msmt = sim.run(circuit, fault_circuit)
                        node = p_it.send(msmt)

        p_L = fail_cnts / n_samples
        std = np.sqrt( var(p_L, n_samples) )
        return p_L, std

# Cell
def calc_subset_occurances(partitions, partition_w_vecs, p_phy_per_partition):
    """Return (weight)x(p_phys) (parition) subset occurance matrix transforming a p_SS vector to a p_L vector"""

    n_partition_elems = np.array([len(p) for p in partitions])
    Aws = np.array([math.binom(w_vec, n_partition_elems, p_phy_per_partition) for w_vec in partition_w_vecs])
    Aws = np.product(Aws, axis=-1) # mult Aws for multi-parameter, i.e. multi-partitions
    return Aws

remap = lambda d, map_fn: {k: map_fn(k,v) for k,v in d.items()}

# Cell
class SubsetSampler(Sampler):
    """Subset Sampler of quantum protocols"""

    # def __init__(self, protocol, err_params):
    #     super().__init__(protocol, err_params)
        # self.fault_gens = map_dict(protocol._circuits, lambda _,circuit: DepolarSS(len(circuit)))

    @staticmethod
    def analytics(circuits, w_maxs, sample_range, err_params, w_exclude={}):
        w_exclude = set((w,) if isinstance(w,int) else w for w in w_exclude)
        w_maxs = [w_maxs] if isinstance(w_maxs, int) else w_maxs

        # circuits = self.protocol._circuits
        w_upto_w_maxs = {c_hash: [tuple(range(w_max+1)) for w_max in w_maxs] for c_hash in circuits.keys()} # order [p1,p2,..]
        w_vecs = remap(w_upto_w_maxs, lambda _,w_list: [w_vec for w_vec in it.product( *w_list ) if w_vec not in w_exclude])

        # self.p_phy_per_partition = np.vstack(list(err_params.values())).T
        # partitions = {c_hash: [partition(circuit, GATE_GROUPS[k]) for ] }
        p_phy_per_partition = np.array([[x * scalar for x in sample_range] for scalar in err_params.values()]).T
        Aws = remap(w_vecs, lambda c_hash, w: calc_subset_occurances(partitions[c_hash], w, p_phy_per_partition))


        # w_vecs = map_dict(w_upto_w_maxs, lambda _,w_list: [w_vec for w_vec in it.product( *w_list ) if w_vec not in w_exclude])
        # Aws = map_dict(w_vecs, lambda c,w: calc_subset_occurances(self.partitions[c], w, self.p_phy_per_partition))
        return Aws, w_vecs

    # def run(self, n_samples, w_max, w_exclude={}, var=math.Wilson_var, eval_fns=None):
    def run(self, n_samples, sample_range, err_params, w_max, w_exclude={}, var=math.Wilson_var, eval_fns={}):

        # Aws, w_vecs = self.analytics(w_max, sample_range, err_params, w_exclude)
        circuits = self.protocol._circuits
        Aws, w_vecs = SubsetSampler.analytics(circuits, w_max, sample_range, err_params, w_exclude)

        d = {n:c for n,c in self.protocol.nodes.data("circuit_hash", default=None) if c}
        visited_cnts    = map_dict(d, lambda _,c_hash: np.zeros(len(w_vecs[c_hash])))
        transition_cnts = map_dict(d, lambda node,c_hash: {s: np.zeros(len(w_vecs[c_hash])) for s in self.protocol.successors(node)})

        for _ in range(n_samples):
            hist = [] # track all (node,weight)s for a protocol run
            p_it = iterate(self.protocol, eval_fns)
            node = next(p_it)
            sim = self.simulator(self.n_qubits_in_protocol)

            while node:
                if node == "EXIT":
                    break
                else:
                    circuit_hash = self.protocol.circuit_hash(node)
                    w_idx = visited_cnts[node].argmin() # balanced weight selector
                    w = w_vecs[circuit_hash][w_idx]
                    hist.append((node,w_idx))
                    msmt = self._sample(sim, circuit_hash, w)
                    visited_cnts[node][w_idx] += 1
                    _node = node # store prev node
                    node = p_it.send(msmt) # exchange with iterator
                    if node: # None: insignificant exit -> no transition
                        transition_cnts[_node][node][w_idx] += 1

        # Calculate statistics

        pws = {n: {succ: tcnts / visited_cnts[n] for succ,tcnts in ntrans.items()} for n,ntrans in transition_cnts.items()}
        unpack_node = lambda n: n if not isinstance(n,(tuple,list,set)) else n[0]

        # p_L
        fail_paths = list(nx.all_simple_paths(self.protocol, 'START', 'EXIT'))
        Aws_wo_excl, w_vecs_wo_excl = SubsetSampler.analytics(circuits, w_maxs, sample_range, err_params, {})
        p_L_up, p_L_low = 0, 0
        for path in fail_paths:
            p_L_up_prod_acc = 1
            p_L_low_prod_acc = 1
            for i in range(1,len(path)-1):
                node, succ_node = path[i:i+2]
                circuit_hash = self.protocol.circuit_hash(node)
                pw = np.sum([Aws[circuit_hash][w] * pws[node][succ_node][w] for w in range(len(w_vecs[circuit_hash]))], axis=0)
                deltas = 1 - np.sum([Aws_wo_excl[circuit_hash][w] for w in range(len(w_vecs_wo_excl[circuit_hash]))], axis=0)
                p_L_low_prod_acc *= pw
                p_L_up_prod_acc *= (pw + deltas)
            p_L_up += p_L_up_prod_acc
            p_L_low += p_L_low_prod_acc

        # v_L
        v_L = 0
        for n1, p_to in pws.items(): # for every node in pws
            c_hash = self.protocol.circuit_hash(n1)
            for succ_node, ps in p_to.items(): # get the pws
                for w_idx, pw in enumerate(ps): # get pw per node

                    vw = var(pw, visited_cnts[n1][w_idx]) # calc. V[pw]
                    Aw = Aws[c_hash][w_idx] # calc. Aw for a single node

                    sum_acc = 0 # sum over all fail paths
                    for path in fail_paths:
                        prod_acc = 1
                        for i in range(1,len(path)-1): # all nodes in a fail path
                            n2, n2_succ = path[i:i+2]
                            if n1 != n2:
                                c_hash2 = self.protocol.circuit_hash(n2)
                                prod_acc *= np.sum([Aws[c_hash2][w] * pws[n2][n2_succ][w] for w in range(len(w_vecs[c_hash2]))], axis=0)
                        sum_acc += prod_acc

                    v_L += vw * Aw**2 * sum_acc**2

        return p_L_up, p_L_low, np.sqrt(v_L)

# Cell
#hide

def calc_w_max(p_max, delta_max, n_partition_elems):
    """Calculate weight cutoff at p_max for delta_max"""

    delta = 1
    for w_max in range(n_partition_elems+1):
        delta -= math.binom(w_max, n_partition_elems, p_max)
        if delta < delta_max:
            break
    return w_max