# AUTOGENERATED! DO NOT EDIT! File to edit: 01_simulator.ipynb (unless otherwise specified).

__all__ = ['Simulator', 'say']

# Cell
from .tools import patch

# Cell
class Simulator:
    """Interface for quantum state simulation"""
    def __init__(self, num_qubits):
        self.n_qubits = num_qubits

# Cell
@patch(Simulator)
def say(self, hi):
    return f'hi {hi}'